array1 = [7,5,10,14,3,9,7]
array2 = [9,10,3,4,2,5,7,1]
print("Array1 is :",array1,"|","Array2 is :",array2)
len_array1 = len(array1)
len_array2 = len(array2)
print("Length of array1 =",len_array1,"|","Length of array2 =",len_array2)
array1.insert(len_array1,15)
print("Insert 15 in array1 :",array1)
Location_of_Seven = array1.index(7)
Location_of_Seven2 = array2.index(7)
print("Location of Seven in array1 =",Location_of_Seven,"|","Location of Seven in array2 =",Location_of_Seven2)
array1.append(1)
array2.append(14)
print("Append 1 in array1 =",array1,"|","Append 14 in array2 =",array2)
array3 = array1.copy()
print("Array3 =",array3)
array3.extend(array2)
print("Array3 + array2 =",array3)
print("Count value of 7 in array3 =",array3.count(7))
array3.sort()
print("Sort array3 =",array3)
array3.remove(7)
print("Remove 7 in array3 =",array3)
array4 = array3.copy()
print("Array 4 =",array4)
array4.reverse()
print("Reverse array4 =",array4)
print("Array3 =",array3,"|","Array4 =",array4)
